[package]
name = "jietu"
version = "0.1.0"
edition = "2024"
description = "轻量原生截图与标注工具（Windows，纯 CPU 渲染）"
license = "GPL-3.0-only"

[profile.release]
lto = "fat"
opt-level = "z"
panic = "abort"
strip = true

[dependencies]
png = "0.18.1"
serde = { version = "1.0.229", features = ["derive"] }
tiny-skia = "0.12.0"
toml = "1.1.6"
windows = { version = "0.62.2", features = ["Win32_Foundation", "Win32_System_Threading", "Win32_System_Registry", "Win32_System_LibraryLoader", "Win32_UI_WindowsAndMessaging", "Win32_UI_Shell", "Win32_UI_Input_KeyboardAndMouse", "Win32_Security", "Win32_Graphics_Gdi"] }

[build-dependencies]
embed-resource = "3.0.11"
